import { cssVariables, darkCssVariables } from "./variables.ts"

/** Selectors that switch a subtree to the dark colour scheme. */
export const darkSchemeSelector = '.dark, [data-theme="dark"]'

const header =
  "/* Generated by @virgulimaginaria/design-tokens. Do not edit: change src/*.ts instead. */"

function declarations(
  variables: Readonly<Record<string, string>>,
  indent: string
): string {
  return Object.entries(variables)
    .map(([name, value]) => `${indent}${name}: ${value};`)
    .join("\n")
}

/**
 * Plain CSS custom properties, usable without Tailwind:
 * `@import "@virgulimaginaria/design-tokens/tokens.css";`
 */
export function renderTokensCss(): string {
  return [
    header,
    "",
    `:root {\n${declarations(cssVariables, "  ")}\n}`,
    "",
    `${darkSchemeSelector} {\n${declarations(darkCssVariables, "  ")}\n}`,
    "",
  ].join("\n")
}

/**
 * Tailwind CSS v4 theme. Registers every token so utilities such as
 * `bg-primary` exist, and always emits the variables (`static`) so they can
 * also be used directly with `var()`.
 */
export function renderTailwindThemeCss(): string {
  return [
    header,
    "",
    `@theme static {\n${declarations(cssVariables, "  ")}\n}`,
    "",
    "@layer base {",
    `  ${darkSchemeSelector} {\n${declarations(darkCssVariables, "    ")}\n  }`,
    "}",
    "",
  ].join("\n")
}
